### ISSUE TITLE
Manage Groups/Clients

### ISSUE THREAD

**Issue by JonnyPillar** [sbarbett/pihole-ansible#6]
Hey, came across this repo as I look to replace my existing ansible PiHole playbook now V6 is here. This repo covers everything I use in Pihole but I cant any references to managing Groups and Clients. I can see references to groups like `groups: [0, 1]` etc but now way to manage them

For an example of how I use them I have these vars outlining the groups for my vlans

```yaml
group_pihole_groups:
  - name: PiHole Default
    enabled: true
    description: The default group
  - name: Cameras
    enabled: true
    description: Cameras VLAN
  - name: Default
    enabled: true
    description: Default VLAN
  - name: IOT
    enabled: true
    description: IOT VLAN

group_pihole_clients:
  - name: 192.168.1.0/24
    comment: Default VLAN
    groups:
      - PiHole Default
      - Default
  - name: 192.168.40.0/24
    comment: Cameras VLAN
    groups:
      - PiHole Default
      - Cameras
  - name: 192.168.50.0/24
    comment: IOT VLAN
    groups:
      - PiHole Default
      - IOT
```

I can then use these to mark specific lists for specific groups etc. Would love to know if this is possible

Thanks
